### PR TITLE
Vxlan vnet route

### PR DESCRIPTION
**Pull request by yue-fred-gao**
sonic-sairedis: support VxLAN vnet route 

* Reference: https://github.com/sonic-net/SONiC/blob/69ad163ad79c8ac1d9e9fa77d0a3d0648067f2f1/doc/vxlan/Vxlan_hld.md
* Introducing SaiObjectDB to manage SAI object relationship.
* Implementing VxLAN encap and decap using VPP data plane.

  Signed-off-by: yuega2@cisco.com

### CODE REVIEW

**Review by VladimirKuk — COMMENTED** [review]
Is there an overview of VPP in SONIC (i.e. HLD) ?
Could you add schema to illustrate both the example (Baremetal to VM connection) and how VPP is handling the VXLAN traffic?
Is there a major difference in how VPP is handling VXLAN comparing to how it is now in SONIC ?

**Comment by yue-fred-gao** [comment]
> Is there an overview of VPP in SONIC (i.e. HLD) ? Could you add schema to illustrate both the example (Baremetal to VM connection) and how VPP is handling the VXLAN traffic? Is there a major difference in how VPP is handling VXLAN comparing to how it is now in SONIC ?

Thanks for the quick feedback. Here is the VPP HLD: [SONICVPP-HLD.md](https://github.com/sonic-net/sonic-platform-vpp/blob/main/docs/HLD/SONICVPP-HLD.md).
I don't see major difference in vxlan handling between vpp and sonic to support vnet peering.
Also, can you clarify what schema are you expecting?

**Comment by VladimirKuk** [comment]
I meant some kind of schema that illustrate VM and Baremetal connectivity.

**Comment by yue-fred-gao** [comment]
> I meant some kind of schema that illustrate VM and Baremetal connectivity. Thank you for the VPP HLD, it answers a lot of questions.

That's great. I updated docs/HLD/vxlan-vnet.md with a diagram showing VM1 and BM1 connectivity via vxlan tunnel. Please check if that helps.

**Review by abdbaig — APPROVED** [review]

**Pull request merged**
